# Generated by Django 3.0.8 on 2020-12-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyTodoList', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Booktitle',
            field=models.TextField(max_length=50),
        ),
    ]
