# Generated by Django 3.0.8 on 2020-12-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyTodoList', '0002_auto_20201207_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Booktitle',
            field=models.TextField(),
        ),
    ]
