# Generated by Django 3.0.8 on 2020-12-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyTodoList', '0003_auto_20201207_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Booktitle',
            field=models.CharField(max_length=500),
        ),
    ]
